name: build-artifacts

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

# mountain.zip -- folder temple -- old_monk.txt & little_monk.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Makeup files
        run: |
          mkdir temple
          touch temple/old_monk.txt
          touch temple/little_monk.sh
      - name: List all files in workdir
        run: |
          ls -R .
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          name: mountain
          path: |
            temple

      - name: Makeup files 2
        run: |
          mkdir temple2
          touch temple2/old_monk2.txt
          touch temple2/little_monk2.sh
      - name: List all files in workdir
        run: |
          ls -R .
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          name: mountain2
          path: |
            temple2

  test:
    runs-on: ubuntu-22.04
    needs: [
       build
    ]
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
      - name: 'Download artifact from other repo'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'dsaltares/godot-wild-jam-18'
          version: 'tags/v0.1.18'
          file: 'plague-linux.zip'
      - name: 'List all downloaded files'
        run: ls -R $GITHUB_WORKSPACE